set SynModuleInfo {
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols
    SUBMODULES {
      {MODELNAME LinearImageFilter_flow_control_loop_pipe_sequential_init RTLNAME LinearImageFilter_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME LinearImageFilter_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols1 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols1 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols1}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols2 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols2 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols2}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols3 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols3 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols3}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols4 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols4 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols4}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols5 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols5 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols5}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols6 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols6 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols6}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols7 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols7 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols7}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols8 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols8 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols8}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols9 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols9 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols9}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols10 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols10 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols10}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols11 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols11 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols11}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols12 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols12 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols12}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols13 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols13 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols13}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols14 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols14 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols14}
  {SRCNAME LinearImageFilter_Pipeline_ker_rows_ker_cols15 MODELNAME LinearImageFilter_Pipeline_ker_rows_ker_cols15 RTLNAME LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols15}
  {SRCNAME LinearImageFilter MODELNAME LinearImageFilter RTLNAME LinearImageFilter IS_TOP 1
    SUBMODULES {
      {MODELNAME LinearImageFilter_mul_32ns_32ns_64_2_1 RTLNAME LinearImageFilter_mul_32ns_32ns_64_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME LinearImageFilter_mul_32s_32s_32_2_1 RTLNAME LinearImageFilter_mul_32s_32s_32_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME LinearImageFilter_udiv_32ns_32ns_32_36_seq_1 RTLNAME LinearImageFilter_udiv_32ns_32ns_32_36_seq_1 BINDTYPE op TYPE udiv IMPL auto_seq LATENCY 35 ALLOW_PRAGMA 1}
      {MODELNAME LinearImageFilter_udiv_32ns_32ns_30_36_seq_1 RTLNAME LinearImageFilter_udiv_32ns_32ns_30_36_seq_1 BINDTYPE op TYPE udiv IMPL auto_seq LATENCY 35 ALLOW_PRAGMA 1}
      {MODELNAME LinearImageFilter_fadd_32ns_32ns_32_5_full_dsp_1 RTLNAME LinearImageFilter_fadd_32ns_32ns_32_5_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME LinearImageFilter_fmul_32ns_32ns_32_4_max_dsp_1 RTLNAME LinearImageFilter_fmul_32ns_32ns_32_4_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME LinearImageFilter_mul_30s_30s_30_2_1 RTLNAME LinearImageFilter_mul_30s_30s_30_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME LinearImageFilter_image_out_m_axi RTLNAME LinearImageFilter_image_out_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME LinearImageFilter_image_in_m_axi RTLNAME LinearImageFilter_image_in_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME LinearImageFilter_kernel_m_axi RTLNAME LinearImageFilter_kernel_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME LinearImageFilter_control_s_axi RTLNAME LinearImageFilter_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
