// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_kernel_AWVALID,
        m_axi_kernel_AWREADY,
        m_axi_kernel_AWADDR,
        m_axi_kernel_AWID,
        m_axi_kernel_AWLEN,
        m_axi_kernel_AWSIZE,
        m_axi_kernel_AWBURST,
        m_axi_kernel_AWLOCK,
        m_axi_kernel_AWCACHE,
        m_axi_kernel_AWPROT,
        m_axi_kernel_AWQOS,
        m_axi_kernel_AWREGION,
        m_axi_kernel_AWUSER,
        m_axi_kernel_WVALID,
        m_axi_kernel_WREADY,
        m_axi_kernel_WDATA,
        m_axi_kernel_WSTRB,
        m_axi_kernel_WLAST,
        m_axi_kernel_WID,
        m_axi_kernel_WUSER,
        m_axi_kernel_ARVALID,
        m_axi_kernel_ARREADY,
        m_axi_kernel_ARADDR,
        m_axi_kernel_ARID,
        m_axi_kernel_ARLEN,
        m_axi_kernel_ARSIZE,
        m_axi_kernel_ARBURST,
        m_axi_kernel_ARLOCK,
        m_axi_kernel_ARCACHE,
        m_axi_kernel_ARPROT,
        m_axi_kernel_ARQOS,
        m_axi_kernel_ARREGION,
        m_axi_kernel_ARUSER,
        m_axi_kernel_RVALID,
        m_axi_kernel_RREADY,
        m_axi_kernel_RDATA,
        m_axi_kernel_RLAST,
        m_axi_kernel_RID,
        m_axi_kernel_RFIFONUM,
        m_axi_kernel_RUSER,
        m_axi_kernel_RRESP,
        m_axi_kernel_BVALID,
        m_axi_kernel_BREADY,
        m_axi_kernel_BRESP,
        m_axi_kernel_BID,
        m_axi_kernel_BUSER,
        m_axi_image_in_AWVALID,
        m_axi_image_in_AWREADY,
        m_axi_image_in_AWADDR,
        m_axi_image_in_AWID,
        m_axi_image_in_AWLEN,
        m_axi_image_in_AWSIZE,
        m_axi_image_in_AWBURST,
        m_axi_image_in_AWLOCK,
        m_axi_image_in_AWCACHE,
        m_axi_image_in_AWPROT,
        m_axi_image_in_AWQOS,
        m_axi_image_in_AWREGION,
        m_axi_image_in_AWUSER,
        m_axi_image_in_WVALID,
        m_axi_image_in_WREADY,
        m_axi_image_in_WDATA,
        m_axi_image_in_WSTRB,
        m_axi_image_in_WLAST,
        m_axi_image_in_WID,
        m_axi_image_in_WUSER,
        m_axi_image_in_ARVALID,
        m_axi_image_in_ARREADY,
        m_axi_image_in_ARADDR,
        m_axi_image_in_ARID,
        m_axi_image_in_ARLEN,
        m_axi_image_in_ARSIZE,
        m_axi_image_in_ARBURST,
        m_axi_image_in_ARLOCK,
        m_axi_image_in_ARCACHE,
        m_axi_image_in_ARPROT,
        m_axi_image_in_ARQOS,
        m_axi_image_in_ARREGION,
        m_axi_image_in_ARUSER,
        m_axi_image_in_RVALID,
        m_axi_image_in_RREADY,
        m_axi_image_in_RDATA,
        m_axi_image_in_RLAST,
        m_axi_image_in_RID,
        m_axi_image_in_RFIFONUM,
        m_axi_image_in_RUSER,
        m_axi_image_in_RRESP,
        m_axi_image_in_BVALID,
        m_axi_image_in_BREADY,
        m_axi_image_in_BRESP,
        m_axi_image_in_BID,
        m_axi_image_in_BUSER,
        mul_ln7,
        padding,
        kernel_dim,
        add_0,
        rows,
        newRow_2,
        col_8,
        empty_27,
        cols,
        empty,
        image_in_offset,
        kernel_offset,
        mul_i,
        mul35_i,
        newCol_2,
        sum_24_out,
        sum_24_out_ap_vld,
        grp_fu_2998_p_din0,
        grp_fu_2998_p_din1,
        grp_fu_2998_p_opcode,
        grp_fu_2998_p_dout0,
        grp_fu_2998_p_ce,
        grp_fu_3002_p_din0,
        grp_fu_3002_p_din1,
        grp_fu_3002_p_dout0,
        grp_fu_3002_p_ce,
        grp_fu_3006_p_din0,
        grp_fu_3006_p_din1,
        grp_fu_3006_p_dout0,
        grp_fu_3006_p_ce,
        grp_fu_939_p_din0,
        grp_fu_939_p_din1,
        grp_fu_939_p_dout0,
        grp_fu_939_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_kernel_AWVALID;
input   m_axi_kernel_AWREADY;
output  [31:0] m_axi_kernel_AWADDR;
output  [0:0] m_axi_kernel_AWID;
output  [31:0] m_axi_kernel_AWLEN;
output  [2:0] m_axi_kernel_AWSIZE;
output  [1:0] m_axi_kernel_AWBURST;
output  [1:0] m_axi_kernel_AWLOCK;
output  [3:0] m_axi_kernel_AWCACHE;
output  [2:0] m_axi_kernel_AWPROT;
output  [3:0] m_axi_kernel_AWQOS;
output  [3:0] m_axi_kernel_AWREGION;
output  [0:0] m_axi_kernel_AWUSER;
output   m_axi_kernel_WVALID;
input   m_axi_kernel_WREADY;
output  [31:0] m_axi_kernel_WDATA;
output  [3:0] m_axi_kernel_WSTRB;
output   m_axi_kernel_WLAST;
output  [0:0] m_axi_kernel_WID;
output  [0:0] m_axi_kernel_WUSER;
output   m_axi_kernel_ARVALID;
input   m_axi_kernel_ARREADY;
output  [31:0] m_axi_kernel_ARADDR;
output  [0:0] m_axi_kernel_ARID;
output  [31:0] m_axi_kernel_ARLEN;
output  [2:0] m_axi_kernel_ARSIZE;
output  [1:0] m_axi_kernel_ARBURST;
output  [1:0] m_axi_kernel_ARLOCK;
output  [3:0] m_axi_kernel_ARCACHE;
output  [2:0] m_axi_kernel_ARPROT;
output  [3:0] m_axi_kernel_ARQOS;
output  [3:0] m_axi_kernel_ARREGION;
output  [0:0] m_axi_kernel_ARUSER;
input   m_axi_kernel_RVALID;
output   m_axi_kernel_RREADY;
input  [31:0] m_axi_kernel_RDATA;
input   m_axi_kernel_RLAST;
input  [0:0] m_axi_kernel_RID;
input  [8:0] m_axi_kernel_RFIFONUM;
input  [0:0] m_axi_kernel_RUSER;
input  [1:0] m_axi_kernel_RRESP;
input   m_axi_kernel_BVALID;
output   m_axi_kernel_BREADY;
input  [1:0] m_axi_kernel_BRESP;
input  [0:0] m_axi_kernel_BID;
input  [0:0] m_axi_kernel_BUSER;
output   m_axi_image_in_AWVALID;
input   m_axi_image_in_AWREADY;
output  [31:0] m_axi_image_in_AWADDR;
output  [0:0] m_axi_image_in_AWID;
output  [31:0] m_axi_image_in_AWLEN;
output  [2:0] m_axi_image_in_AWSIZE;
output  [1:0] m_axi_image_in_AWBURST;
output  [1:0] m_axi_image_in_AWLOCK;
output  [3:0] m_axi_image_in_AWCACHE;
output  [2:0] m_axi_image_in_AWPROT;
output  [3:0] m_axi_image_in_AWQOS;
output  [3:0] m_axi_image_in_AWREGION;
output  [0:0] m_axi_image_in_AWUSER;
output   m_axi_image_in_WVALID;
input   m_axi_image_in_WREADY;
output  [31:0] m_axi_image_in_WDATA;
output  [3:0] m_axi_image_in_WSTRB;
output   m_axi_image_in_WLAST;
output  [0:0] m_axi_image_in_WID;
output  [0:0] m_axi_image_in_WUSER;
output   m_axi_image_in_ARVALID;
input   m_axi_image_in_ARREADY;
output  [31:0] m_axi_image_in_ARADDR;
output  [0:0] m_axi_image_in_ARID;
output  [31:0] m_axi_image_in_ARLEN;
output  [2:0] m_axi_image_in_ARSIZE;
output  [1:0] m_axi_image_in_ARBURST;
output  [1:0] m_axi_image_in_ARLOCK;
output  [3:0] m_axi_image_in_ARCACHE;
output  [2:0] m_axi_image_in_ARPROT;
output  [3:0] m_axi_image_in_ARQOS;
output  [3:0] m_axi_image_in_ARREGION;
output  [0:0] m_axi_image_in_ARUSER;
input   m_axi_image_in_RVALID;
output   m_axi_image_in_RREADY;
input  [31:0] m_axi_image_in_RDATA;
input   m_axi_image_in_RLAST;
input  [0:0] m_axi_image_in_RID;
input  [8:0] m_axi_image_in_RFIFONUM;
input  [0:0] m_axi_image_in_RUSER;
input  [1:0] m_axi_image_in_RRESP;
input   m_axi_image_in_BVALID;
output   m_axi_image_in_BREADY;
input  [1:0] m_axi_image_in_BRESP;
input  [0:0] m_axi_image_in_BID;
input  [0:0] m_axi_image_in_BUSER;
input  [63:0] mul_ln7;
input  [7:0] padding;
input  [31:0] kernel_dim;
input  [31:0] add_0;
input  [31:0] rows;
input  [29:0] newRow_2;
input  [31:0] col_8;
input  [30:0] empty_27;
input  [31:0] cols;
input  [29:0] empty;
input  [31:0] image_in_offset;
input  [31:0] kernel_offset;
input  [29:0] mul_i;
input  [29:0] mul35_i;
input  [29:0] newCol_2;
output  [31:0] sum_24_out;
output   sum_24_out_ap_vld;
output  [31:0] grp_fu_2998_p_din0;
output  [31:0] grp_fu_2998_p_din1;
output  [1:0] grp_fu_2998_p_opcode;
input  [31:0] grp_fu_2998_p_dout0;
output   grp_fu_2998_p_ce;
output  [31:0] grp_fu_3002_p_din0;
output  [31:0] grp_fu_3002_p_din1;
input  [31:0] grp_fu_3002_p_dout0;
output   grp_fu_3002_p_ce;
output  [29:0] grp_fu_3006_p_din0;
output  [29:0] grp_fu_3006_p_din1;
input  [29:0] grp_fu_3006_p_dout0;
output   grp_fu_3006_p_ce;
output  [31:0] grp_fu_939_p_din0;
output  [31:0] grp_fu_939_p_din1;
input  [31:0] grp_fu_939_p_dout0;
output   grp_fu_939_p_ce;

reg ap_idle;
reg m_axi_kernel_ARVALID;
reg m_axi_kernel_RREADY;
reg m_axi_image_in_ARVALID;
reg m_axi_image_in_RREADY;
reg sum_24_out_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln39_reg_870;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    kernel_blk_n_AR;
wire    ap_block_pp0_stage0;
reg   [0:0] or_ln69_4_reg_958;
wire    ap_block_pp0_stage4_11001;
reg    ap_predicate_pred208_state6;
reg    kernel_blk_n_R;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] or_ln69_4_reg_958_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg    ap_predicate_pred231_state14;
reg    image_in_blk_n_AR;
reg    ap_predicate_pred247_state9;
reg    image_in_blk_n_R;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] or_ln69_4_reg_958_pp0_iter2_reg;
reg    ap_predicate_op140_readreq_state6;
reg    ap_block_state6_io;
reg    ap_block_pp0_stage0_11001;
reg    ap_predicate_pred265_state17;
reg   [29:0] newCol_6_ph_8_reg_263;
wire   [31:0] p_cast_fu_304_p1;
reg   [31:0] p_cast_reg_865;
wire   [0:0] icmp_ln39_fu_331_p2;
reg    ap_predicate_op169_read_state17;
reg    ap_block_state17_pp0_stage1_iter3;
reg    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln39_reg_870_pp0_iter1_reg;
reg   [0:0] icmp_ln39_reg_870_pp0_iter2_reg;
reg   [0:0] icmp_ln39_reg_870_pp0_iter3_reg;
wire   [63:0] add_ln39_fu_336_p2;
reg   [63:0] add_ln39_reg_874;
reg   [31:0] j_load_reg_879;
wire   [0:0] icmp_ln43_fu_348_p2;
reg   [0:0] icmp_ln43_reg_884;
wire  signed [31:0] select_ln39_fu_359_p3;
reg  signed [31:0] select_ln39_reg_889;
wire   [31:0] select_ln24_fu_367_p3;
reg   [31:0] select_ln24_reg_896;
wire   [31:0] newRow_fu_373_p2;
reg   [31:0] newRow_reg_902;
wire   [29:0] empty_55_fu_377_p1;
reg   [29:0] empty_55_reg_911;
wire   [0:0] tmp_5_fu_385_p3;
reg   [0:0] tmp_5_reg_916;
wire   [29:0] newRow_9_fu_420_p3;
reg   [29:0] newRow_9_reg_922;
wire   [31:0] newCol_fu_431_p2;
reg   [31:0] newCol_reg_927;
wire   [29:0] trunc_ln27_fu_437_p1;
reg   [29:0] trunc_ln27_reg_936;
wire   [30:0] trunc_ln27_4_fu_441_p1;
reg   [30:0] trunc_ln27_4_reg_941;
reg   [0:0] tmp_6_reg_946;
wire   [29:0] trunc_ln55_fu_463_p1;
reg   [29:0] trunc_ln55_reg_953;
reg    ap_predicate_op155_readreq_state9;
reg    ap_block_state9_io;
reg    ap_predicate_op166_read_state14;
reg    ap_block_state14_pp0_stage3_iter2;
reg    ap_block_pp0_stage3_11001;
wire   [0:0] or_ln69_4_fu_487_p2;
reg   [0:0] or_ln69_4_reg_958_pp0_iter3_reg;
reg   [0:0] or_ln69_4_reg_958_pp0_iter4_reg;
wire   [31:0] newRow_11_fu_516_p3;
reg   [31:0] newRow_11_reg_962;
wire   [29:0] trunc_ln26_fu_522_p1;
reg   [29:0] trunc_ln26_reg_967;
wire   [31:0] newCol_11_fu_549_p3;
reg   [31:0] newCol_11_reg_973;
wire   [29:0] trunc_ln27_6_fu_555_p1;
reg   [29:0] trunc_ln27_6_reg_978;
wire   [29:0] newCol_9_fu_584_p3;
wire   [29:0] newRow_13_fu_611_p3;
wire   [29:0] newCol_13_fu_638_p3;
reg   [29:0] trunc_ln55_3_reg_999;
reg   [29:0] mul_ln55_reg_1010;
reg   [29:0] trunc_ln55_s_reg_1015;
reg   [31:0] kernel_addr_read_reg_1026;
reg   [31:0] image_in_addr_read_reg_1031;
wire   [31:0] bitcast_ln55_fu_742_p1;
wire   [31:0] bitcast_ln55_2_fu_746_p1;
reg   [31:0] mul21_8_reg_1046;
reg   [31:0] sum_2_reg_1056;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [29:0] ap_phi_reg_pp0_iter0_newCol_6_ph_8_reg_263;
reg   [29:0] ap_phi_reg_pp0_iter1_newCol_6_ph_8_reg_263;
reg  signed [29:0] ap_phi_reg_pp0_iter0_newRow_6_ph_8_reg_275;
reg  signed [29:0] ap_phi_reg_pp0_iter1_newRow_6_ph_8_reg_275;
wire  signed [31:0] sext_ln55_2_fu_676_p1;
wire  signed [31:0] sext_ln55_fu_732_p1;
reg   [31:0] j_fu_126;
wire   [31:0] add_ln43_fu_686_p2;
wire    ap_loop_init;
reg   [31:0] i_fu_130;
reg   [63:0] indvar_flatten175_fu_134;
reg   [31:0] sum_fu_138;
reg    ap_predicate_pred506_state27;
reg   [31:0] ap_sig_allocacmp_sum_load_2;
reg    ap_block_pp0_stage1_01001;
wire    ap_block_pp0_stage2;
wire  signed [31:0] icmp_ln43_fu_348_p1;
wire   [31:0] add_ln39_2_fu_353_p2;
wire   [30:0] empty_56_fu_381_p1;
wire   [30:0] newRow_8_fu_393_p3;
wire   [31:0] newRow_58_cast78_fu_401_p1;
wire   [0:0] ult43_fu_409_p2;
wire   [0:0] rev44_fu_414_p2;
wire   [29:0] empty_57_fu_405_p1;
wire   [31:0] sub_ln48_fu_427_p2;
wire   [0:0] ult_fu_453_p2;
wire   [0:0] icmp_ln69_fu_467_p2;
wire   [0:0] xor_ln69_fu_471_p2;
wire   [0:0] rev42_fu_457_p2;
wire   [0:0] or_ln69_3_fu_482_p2;
wire   [0:0] or_ln69_fu_477_p2;
wire   [0:0] abscond47_fu_498_p2;
wire   [31:0] neg46_fu_493_p2;
wire   [31:0] abs48_fu_503_p3;
wire   [31:0] newRow_10_fu_510_p2;
wire   [0:0] abscond50_fu_531_p2;
wire   [31:0] neg49_fu_526_p2;
wire   [31:0] abs51_fu_536_p3;
wire   [31:0] newCol_10_fu_543_p2;
wire   [30:0] newCol_8_fu_559_p3;
wire   [31:0] zext_ln27_fu_565_p1;
wire   [0:0] icmp_ln86_fu_573_p2;
wire   [0:0] xor_ln86_fu_578_p2;
wire   [29:0] trunc_ln27_5_fu_569_p1;
wire    ap_block_pp0_stage4;
wire   [0:0] icmp_ln96_fu_591_p2;
wire   [29:0] add_ln98_fu_601_p2;
wire   [0:0] xor_ln96_fu_595_p2;
wire   [29:0] newRow_12_fu_606_p2;
wire   [0:0] icmp_ln104_fu_618_p2;
wire   [29:0] add_ln106_fu_628_p2;
wire   [0:0] xor_ln104_fu_622_p2;
wire   [29:0] newCol_12_fu_633_p2;
wire   [29:0] trunc_ln55_2_fu_645_p1;
wire   [29:0] add_ln55_5_fu_648_p2;
wire   [31:0] shl_ln55_2_fu_653_p3;
wire   [31:0] add_ln55_6_fu_661_p2;
wire   [29:0] add_ln55_fu_704_p2;
wire   [31:0] shl_ln55_s_fu_709_p3;
wire   [31:0] add_ln55_4_fu_717_p2;
reg    grp_fu_287_ce;
reg    ap_predicate_op177_fadd_state22;
reg    grp_fu_291_ce;
reg    grp_fu_295_ce;
reg    grp_fu_300_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage1;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to5;
reg    ap_done_pending_pp0;
wire    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_block_pp0_stage1_00001;
reg    ap_condition_820;
reg    ap_condition_466;
reg    ap_condition_456;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 j_fu_126 = 32'd0;
#0 i_fu_130 = 32'd0;
#0 indvar_flatten175_fu_134 = 64'd0;
#0 sum_fu_138 = 32'd0;
#0 ap_done_reg = 1'b0;
end

LinearImageFilter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_820)) begin
        if ((or_ln69_4_fu_487_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_newCol_6_ph_8_reg_263 <= trunc_ln27_reg_936;
        end else if (((or_ln69_4_fu_487_p2 == 1'd1) & (padding == 8'd1))) begin
            ap_phi_reg_pp0_iter0_newCol_6_ph_8_reg_263 <= newCol_9_fu_584_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_820)) begin
        if ((or_ln69_4_fu_487_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_newRow_6_ph_8_reg_275 <= empty_55_reg_911;
        end else if (((or_ln69_4_fu_487_p2 == 1'd1) & (padding == 8'd1))) begin
            ap_phi_reg_pp0_iter0_newRow_6_ph_8_reg_275 <= newRow_9_reg_922;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_456)) begin
        if ((1'b1 == ap_condition_466)) begin
            ap_phi_reg_pp0_iter1_newCol_6_ph_8_reg_263 <= newCol_13_fu_638_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_newCol_6_ph_8_reg_263 <= ap_phi_reg_pp0_iter0_newCol_6_ph_8_reg_263;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_456)) begin
        if ((1'b1 == ap_condition_466)) begin
            ap_phi_reg_pp0_iter1_newRow_6_ph_8_reg_275 <= newRow_13_fu_611_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_newRow_6_ph_8_reg_275 <= ap_phi_reg_pp0_iter0_newRow_6_ph_8_reg_275;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_130 <= 32'd0;
        end else if (((icmp_ln39_reg_870 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_130 <= select_ln39_reg_889;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten175_fu_134 <= 64'd0;
        end else if (((icmp_ln39_reg_870 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten175_fu_134 <= add_ln39_reg_874;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_126 <= 32'd0;
        end else if (((icmp_ln39_reg_870 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_126 <= add_ln43_fu_686_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_fu_138 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_pred506_state27 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_fu_138 <= sum_2_reg_1056;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln39_reg_874 <= add_ln39_fu_336_p2;
        icmp_ln39_reg_870 <= icmp_ln39_fu_331_p2;
        icmp_ln39_reg_870_pp0_iter1_reg <= icmp_ln39_reg_870;
        icmp_ln39_reg_870_pp0_iter2_reg <= icmp_ln39_reg_870_pp0_iter1_reg;
        icmp_ln39_reg_870_pp0_iter3_reg <= icmp_ln39_reg_870_pp0_iter2_reg;
        icmp_ln43_reg_884 <= icmp_ln43_fu_348_p2;
        image_in_addr_read_reg_1031 <= m_axi_image_in_RDATA;
        j_load_reg_879 <= j_fu_126;
        mul_ln55_reg_1010 <= grp_fu_3006_p_dout0;
        select_ln39_reg_889 <= select_ln39_fu_359_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_predicate_pred208_state6 <= ((((icmp_ln39_reg_870 == 1'd0) & (padding == 8'd1)) | ((icmp_ln39_reg_870 == 1'd0) & (padding == 8'd2))) | ((icmp_ln39_reg_870 == 1'd0) & (or_ln69_4_reg_958 == 1'd0)));
        trunc_ln55_3_reg_999 <= {{add_ln55_6_fu_661_p2[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_predicate_pred231_state14 <= ((or_ln69_4_reg_958_pp0_iter1_reg == 1'd0) | ((padding == 8'd1) | (padding == 8'd2)));
        ap_predicate_pred247_state9 <= ((or_ln69_4_reg_958 == 1'd0) | ((padding == 8'd1) | (padding == 8'd2)));
        empty_55_reg_911 <= empty_55_fu_377_p1;
        newCol_reg_927 <= newCol_fu_431_p2;
        newRow_9_reg_922 <= newRow_9_fu_420_p3;
        newRow_reg_902 <= newRow_fu_373_p2;
        select_ln24_reg_896 <= select_ln24_fu_367_p3;
        tmp_5_reg_916 <= newRow_fu_373_p2[32'd31];
        tmp_6_reg_946 <= newCol_fu_431_p2[32'd31];
        trunc_ln27_4_reg_941 <= trunc_ln27_4_fu_441_p1;
        trunc_ln27_reg_936 <= trunc_ln27_fu_437_p1;
        trunc_ln55_s_reg_1015 <= {{add_ln55_4_fu_717_p2[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_predicate_pred265_state17 <= ((or_ln69_4_reg_958_pp0_iter2_reg == 1'd0) | ((padding == 8'd1) | (padding == 8'd2)));
        ap_predicate_pred506_state27 <= ((or_ln69_4_reg_958_pp0_iter4_reg == 1'd0) | ((padding == 8'd1) | (padding == 8'd2)));
        mul21_8_reg_1046 <= grp_fu_3002_p_dout0;
        p_cast_reg_865[30 : 0] <= p_cast_fu_304_p1[30 : 0];
        sum_2_reg_1056 <= grp_fu_2998_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        kernel_addr_read_reg_1026 <= m_axi_kernel_RDATA;
        newCol_11_reg_973 <= newCol_11_fu_549_p3;
        newRow_11_reg_962 <= newRow_11_fu_516_p3;
        or_ln69_4_reg_958 <= or_ln69_4_fu_487_p2;
        or_ln69_4_reg_958_pp0_iter1_reg <= or_ln69_4_reg_958;
        or_ln69_4_reg_958_pp0_iter2_reg <= or_ln69_4_reg_958_pp0_iter1_reg;
        or_ln69_4_reg_958_pp0_iter3_reg <= or_ln69_4_reg_958_pp0_iter2_reg;
        or_ln69_4_reg_958_pp0_iter4_reg <= or_ln69_4_reg_958_pp0_iter3_reg;
        trunc_ln26_reg_967 <= trunc_ln26_fu_522_p1;
        trunc_ln27_6_reg_978 <= trunc_ln27_6_fu_555_p1;
        trunc_ln55_reg_953 <= trunc_ln55_fu_463_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        newCol_6_ph_8_reg_263 <= ap_phi_reg_pp0_iter1_newCol_6_ph_8_reg_263;
    end
end

always @ (*) begin
    if (((icmp_ln39_reg_870 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln39_reg_870_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_predicate_pred506_state27 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_sum_load_2 = sum_2_reg_1056;
    end else begin
        ap_sig_allocacmp_sum_load_2 = sum_fu_138;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_fu_287_ce = 1'b1;
    end else begin
        grp_fu_287_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_fu_291_ce = 1'b1;
    end else begin
        grp_fu_291_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_295_ce = 1'b1;
    end else begin
        grp_fu_295_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_300_ce = 1'b1;
    end else begin
        grp_fu_300_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_pred247_state9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        image_in_blk_n_AR = m_axi_image_in_ARREADY;
    end else begin
        image_in_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_pred265_state17 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        image_in_blk_n_R = m_axi_image_in_RVALID;
    end else begin
        image_in_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_pred208_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_blk_n_AR = m_axi_kernel_ARREADY;
    end else begin
        kernel_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred231_state14 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        kernel_blk_n_R = m_axi_kernel_RVALID;
    end else begin
        kernel_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op155_readreq_state9 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        m_axi_image_in_ARVALID = 1'b1;
    end else begin
        m_axi_image_in_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op169_read_state17 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m_axi_image_in_RREADY = 1'b1;
    end else begin
        m_axi_image_in_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op140_readreq_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_kernel_ARVALID = 1'b1;
    end else begin
        m_axi_kernel_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op166_read_state14 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        m_axi_kernel_RREADY = 1'b1;
    end else begin
        m_axi_kernel_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln39_reg_870_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_24_out_ap_vld = 1'b1;
    end else begin
        sum_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs48_fu_503_p3 = ((abscond47_fu_498_p2[0:0] == 1'b1) ? newRow_reg_902 : neg46_fu_493_p2);

assign abs51_fu_536_p3 = ((abscond50_fu_531_p2[0:0] == 1'b1) ? newCol_reg_927 : neg49_fu_526_p2);

assign abscond47_fu_498_p2 = (($signed(newRow_reg_902) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign abscond50_fu_531_p2 = (($signed(newCol_reg_927) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign add_ln106_fu_628_p2 = ($signed(mul35_i) + $signed(30'd1073741823));

assign add_ln39_2_fu_353_p2 = (i_fu_130 + 32'd1);

assign add_ln39_fu_336_p2 = (indvar_flatten175_fu_134 + 64'd1);

assign add_ln43_fu_686_p2 = (select_ln24_reg_896 + 32'd1);

assign add_ln55_4_fu_717_p2 = (shl_ln55_s_fu_709_p3 + image_in_offset);

assign add_ln55_5_fu_648_p2 = (trunc_ln55_2_fu_645_p1 + trunc_ln55_reg_953);

assign add_ln55_6_fu_661_p2 = (shl_ln55_2_fu_653_p3 + kernel_offset);

assign add_ln55_fu_704_p2 = (mul_ln55_reg_1010 + newCol_6_ph_8_reg_263);

assign add_ln98_fu_601_p2 = ($signed(mul_i) + $signed(30'd1073741823));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_00001 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage1_iter3));
end

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage1_iter3));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage1_iter3));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage1_iter3));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage3_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage3_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage3_iter2 = ((ap_predicate_op166_read_state14 == 1'b1) & (m_axi_kernel_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state17_pp0_stage1_iter3 = ((ap_predicate_op169_read_state17 == 1'b1) & (m_axi_image_in_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state6_io = ((m_axi_kernel_ARREADY == 1'b0) & (ap_predicate_op140_readreq_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state9_io = ((ap_predicate_op155_readreq_state9 == 1'b1) & (m_axi_image_in_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_456 = ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4));
end

always @ (*) begin
    ap_condition_466 = ((icmp_ln39_reg_870 == 1'd0) & (or_ln69_4_reg_958 == 1'd1) & (padding == 8'd2));
end

always @ (*) begin
    ap_condition_820 = ((icmp_ln39_reg_870 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

always @ (*) begin
    ap_predicate_op140_readreq_state6 = ((((icmp_ln39_reg_870 == 1'd0) & (padding == 8'd1)) | ((icmp_ln39_reg_870 == 1'd0) & (padding == 8'd2))) | ((icmp_ln39_reg_870 == 1'd0) & (or_ln69_4_reg_958 == 1'd0)));
end

always @ (*) begin
    ap_predicate_op155_readreq_state9 = ((or_ln69_4_reg_958 == 1'd0) | ((padding == 8'd1) | (padding == 8'd2)));
end

always @ (*) begin
    ap_predicate_op166_read_state14 = ((or_ln69_4_reg_958_pp0_iter1_reg == 1'd0) | ((padding == 8'd1) | (padding == 8'd2)));
end

always @ (*) begin
    ap_predicate_op169_read_state17 = ((or_ln69_4_reg_958_pp0_iter2_reg == 1'd0) | ((padding == 8'd1) | (padding == 8'd2)));
end

always @ (*) begin
    ap_predicate_op177_fadd_state22 = ((or_ln69_4_reg_958_pp0_iter3_reg == 1'd0) | ((padding == 8'd1) | (padding == 8'd2)));
end

assign bitcast_ln55_2_fu_746_p1 = kernel_addr_read_reg_1026;

assign bitcast_ln55_fu_742_p1 = image_in_addr_read_reg_1031;

assign empty_55_fu_377_p1 = newRow_fu_373_p2[29:0];

assign empty_56_fu_381_p1 = newRow_fu_373_p2[30:0];

assign empty_57_fu_405_p1 = newRow_8_fu_393_p3[29:0];

assign grp_fu_2998_p_ce = grp_fu_287_ce;

assign grp_fu_2998_p_din0 = ap_sig_allocacmp_sum_load_2;

assign grp_fu_2998_p_din1 = mul21_8_reg_1046;

assign grp_fu_2998_p_opcode = 2'd0;

assign grp_fu_3002_p_ce = grp_fu_291_ce;

assign grp_fu_3002_p_din0 = bitcast_ln55_fu_742_p1;

assign grp_fu_3002_p_din1 = bitcast_ln55_2_fu_746_p1;

assign grp_fu_3006_p_ce = grp_fu_295_ce;

assign grp_fu_3006_p_din0 = ap_phi_reg_pp0_iter1_newRow_6_ph_8_reg_275;

assign grp_fu_3006_p_din1 = empty;

assign grp_fu_939_p_ce = grp_fu_300_ce;

assign grp_fu_939_p_din0 = select_ln39_reg_889;

assign grp_fu_939_p_din1 = kernel_dim;

assign icmp_ln104_fu_618_p2 = ((newCol_11_reg_973 < cols) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_331_p2 = ((indvar_flatten175_fu_134 == mul_ln7) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_348_p1 = kernel_dim;

assign icmp_ln43_fu_348_p2 = ((j_fu_126 == icmp_ln43_fu_348_p1) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_467_p2 = ((newCol_reg_927 < cols) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_573_p2 = ((zext_ln27_fu_565_p1 < cols) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_591_p2 = ((newRow_11_reg_962 < rows) ? 1'b1 : 1'b0);

assign m_axi_image_in_ARADDR = sext_ln55_fu_732_p1;

assign m_axi_image_in_ARBURST = 2'd0;

assign m_axi_image_in_ARCACHE = 4'd0;

assign m_axi_image_in_ARID = 1'd0;

assign m_axi_image_in_ARLEN = 32'd1;

assign m_axi_image_in_ARLOCK = 2'd0;

assign m_axi_image_in_ARPROT = 3'd0;

assign m_axi_image_in_ARQOS = 4'd0;

assign m_axi_image_in_ARREGION = 4'd0;

assign m_axi_image_in_ARSIZE = 3'd0;

assign m_axi_image_in_ARUSER = 1'd0;

assign m_axi_image_in_AWADDR = 32'd0;

assign m_axi_image_in_AWBURST = 2'd0;

assign m_axi_image_in_AWCACHE = 4'd0;

assign m_axi_image_in_AWID = 1'd0;

assign m_axi_image_in_AWLEN = 32'd0;

assign m_axi_image_in_AWLOCK = 2'd0;

assign m_axi_image_in_AWPROT = 3'd0;

assign m_axi_image_in_AWQOS = 4'd0;

assign m_axi_image_in_AWREGION = 4'd0;

assign m_axi_image_in_AWSIZE = 3'd0;

assign m_axi_image_in_AWUSER = 1'd0;

assign m_axi_image_in_AWVALID = 1'b0;

assign m_axi_image_in_BREADY = 1'b0;

assign m_axi_image_in_WDATA = 32'd0;

assign m_axi_image_in_WID = 1'd0;

assign m_axi_image_in_WLAST = 1'b0;

assign m_axi_image_in_WSTRB = 4'd0;

assign m_axi_image_in_WUSER = 1'd0;

assign m_axi_image_in_WVALID = 1'b0;

assign m_axi_kernel_ARADDR = sext_ln55_2_fu_676_p1;

assign m_axi_kernel_ARBURST = 2'd0;

assign m_axi_kernel_ARCACHE = 4'd0;

assign m_axi_kernel_ARID = 1'd0;

assign m_axi_kernel_ARLEN = 32'd1;

assign m_axi_kernel_ARLOCK = 2'd0;

assign m_axi_kernel_ARPROT = 3'd0;

assign m_axi_kernel_ARQOS = 4'd0;

assign m_axi_kernel_ARREGION = 4'd0;

assign m_axi_kernel_ARSIZE = 3'd0;

assign m_axi_kernel_ARUSER = 1'd0;

assign m_axi_kernel_AWADDR = 32'd0;

assign m_axi_kernel_AWBURST = 2'd0;

assign m_axi_kernel_AWCACHE = 4'd0;

assign m_axi_kernel_AWID = 1'd0;

assign m_axi_kernel_AWLEN = 32'd0;

assign m_axi_kernel_AWLOCK = 2'd0;

assign m_axi_kernel_AWPROT = 3'd0;

assign m_axi_kernel_AWQOS = 4'd0;

assign m_axi_kernel_AWREGION = 4'd0;

assign m_axi_kernel_AWSIZE = 3'd0;

assign m_axi_kernel_AWUSER = 1'd0;

assign m_axi_kernel_AWVALID = 1'b0;

assign m_axi_kernel_BREADY = 1'b0;

assign m_axi_kernel_WDATA = 32'd0;

assign m_axi_kernel_WID = 1'd0;

assign m_axi_kernel_WLAST = 1'b0;

assign m_axi_kernel_WSTRB = 4'd0;

assign m_axi_kernel_WUSER = 1'd0;

assign m_axi_kernel_WVALID = 1'b0;

assign neg46_fu_493_p2 = (32'd0 - newRow_reg_902);

assign neg49_fu_526_p2 = (32'd0 - newCol_reg_927);

assign newCol_10_fu_543_p2 = ($signed(abs51_fu_536_p3) + $signed(32'd4294967295));

assign newCol_11_fu_549_p3 = ((tmp_6_reg_946[0:0] == 1'b1) ? newCol_10_fu_543_p2 : newCol_reg_927);

assign newCol_12_fu_633_p2 = (add_ln106_fu_628_p2 - trunc_ln27_6_reg_978);

assign newCol_13_fu_638_p3 = ((xor_ln104_fu_622_p2[0:0] == 1'b1) ? newCol_12_fu_633_p2 : trunc_ln27_6_reg_978);

assign newCol_8_fu_559_p3 = ((tmp_6_reg_946[0:0] == 1'b1) ? 31'd0 : trunc_ln27_4_reg_941);

assign newCol_9_fu_584_p3 = ((xor_ln86_fu_578_p2[0:0] == 1'b1) ? newCol_2 : trunc_ln27_5_fu_569_p1);

assign newCol_fu_431_p2 = (select_ln24_fu_367_p3 + sub_ln48_fu_427_p2);

assign newRow_10_fu_510_p2 = ($signed(abs48_fu_503_p3) + $signed(32'd4294967295));

assign newRow_11_fu_516_p3 = ((tmp_5_reg_916[0:0] == 1'b1) ? newRow_10_fu_510_p2 : newRow_reg_902);

assign newRow_12_fu_606_p2 = (add_ln98_fu_601_p2 - trunc_ln26_reg_967);

assign newRow_13_fu_611_p3 = ((xor_ln96_fu_595_p2[0:0] == 1'b1) ? newRow_12_fu_606_p2 : trunc_ln26_reg_967);

assign newRow_58_cast78_fu_401_p1 = newRow_8_fu_393_p3;

assign newRow_8_fu_393_p3 = ((tmp_5_fu_385_p3[0:0] == 1'b1) ? 31'd0 : empty_56_fu_381_p1);

assign newRow_9_fu_420_p3 = ((rev44_fu_414_p2[0:0] == 1'b1) ? newRow_2 : empty_57_fu_405_p1);

assign newRow_fu_373_p2 = ($signed(select_ln39_reg_889) + $signed(add_0));

assign or_ln69_3_fu_482_p2 = (tmp_5_reg_916 | rev42_fu_457_p2);

assign or_ln69_4_fu_487_p2 = (or_ln69_fu_477_p2 | or_ln69_3_fu_482_p2);

assign or_ln69_fu_477_p2 = (xor_ln69_fu_471_p2 | tmp_6_reg_946);

assign p_cast_fu_304_p1 = empty_27;

assign rev42_fu_457_p2 = (ult_fu_453_p2 ^ 1'd1);

assign rev44_fu_414_p2 = (ult43_fu_409_p2 ^ 1'd1);

assign select_ln24_fu_367_p3 = ((icmp_ln43_reg_884[0:0] == 1'b1) ? 32'd0 : j_load_reg_879);

assign select_ln39_fu_359_p3 = ((icmp_ln43_fu_348_p2[0:0] == 1'b1) ? add_ln39_2_fu_353_p2 : i_fu_130);

assign sext_ln55_2_fu_676_p1 = $signed(trunc_ln55_3_reg_999);

assign sext_ln55_fu_732_p1 = $signed(trunc_ln55_s_reg_1015);

assign shl_ln55_2_fu_653_p3 = {{add_ln55_5_fu_648_p2}, {2'd0}};

assign shl_ln55_s_fu_709_p3 = {{add_ln55_fu_704_p2}, {2'd0}};

assign sub_ln48_fu_427_p2 = (col_8 - p_cast_reg_865);

assign sum_24_out = sum_fu_138;

assign tmp_5_fu_385_p3 = newRow_fu_373_p2[32'd31];

assign trunc_ln26_fu_522_p1 = newRow_11_fu_516_p3[29:0];

assign trunc_ln27_4_fu_441_p1 = newCol_fu_431_p2[30:0];

assign trunc_ln27_5_fu_569_p1 = newCol_8_fu_559_p3[29:0];

assign trunc_ln27_6_fu_555_p1 = newCol_11_fu_549_p3[29:0];

assign trunc_ln27_fu_437_p1 = newCol_fu_431_p2[29:0];

assign trunc_ln55_2_fu_645_p1 = select_ln24_reg_896[29:0];

assign trunc_ln55_fu_463_p1 = grp_fu_939_p_dout0[29:0];

assign ult43_fu_409_p2 = ((newRow_58_cast78_fu_401_p1 < rows) ? 1'b1 : 1'b0);

assign ult_fu_453_p2 = ((newRow_reg_902 < rows) ? 1'b1 : 1'b0);

assign xor_ln104_fu_622_p2 = (icmp_ln104_fu_618_p2 ^ 1'd1);

assign xor_ln69_fu_471_p2 = (icmp_ln69_fu_467_p2 ^ 1'd1);

assign xor_ln86_fu_578_p2 = (icmp_ln86_fu_573_p2 ^ 1'd1);

assign xor_ln96_fu_595_p2 = (icmp_ln96_fu_591_p2 ^ 1'd1);

assign zext_ln27_fu_565_p1 = newCol_8_fu_559_p3;

always @ (posedge ap_clk) begin
    p_cast_reg_865[31] <= 1'b0;
end

endmodule //LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_ker_cols8
