// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_loop_ker_cols_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_kernel_AWVALID,
        m_axi_kernel_AWREADY,
        m_axi_kernel_AWADDR,
        m_axi_kernel_AWID,
        m_axi_kernel_AWLEN,
        m_axi_kernel_AWSIZE,
        m_axi_kernel_AWBURST,
        m_axi_kernel_AWLOCK,
        m_axi_kernel_AWCACHE,
        m_axi_kernel_AWPROT,
        m_axi_kernel_AWQOS,
        m_axi_kernel_AWREGION,
        m_axi_kernel_AWUSER,
        m_axi_kernel_WVALID,
        m_axi_kernel_WREADY,
        m_axi_kernel_WDATA,
        m_axi_kernel_WSTRB,
        m_axi_kernel_WLAST,
        m_axi_kernel_WID,
        m_axi_kernel_WUSER,
        m_axi_kernel_ARVALID,
        m_axi_kernel_ARREADY,
        m_axi_kernel_ARADDR,
        m_axi_kernel_ARID,
        m_axi_kernel_ARLEN,
        m_axi_kernel_ARSIZE,
        m_axi_kernel_ARBURST,
        m_axi_kernel_ARLOCK,
        m_axi_kernel_ARCACHE,
        m_axi_kernel_ARPROT,
        m_axi_kernel_ARQOS,
        m_axi_kernel_ARREGION,
        m_axi_kernel_ARUSER,
        m_axi_kernel_RVALID,
        m_axi_kernel_RREADY,
        m_axi_kernel_RDATA,
        m_axi_kernel_RLAST,
        m_axi_kernel_RID,
        m_axi_kernel_RFIFONUM,
        m_axi_kernel_RUSER,
        m_axi_kernel_RRESP,
        m_axi_kernel_BVALID,
        m_axi_kernel_BREADY,
        m_axi_kernel_BRESP,
        m_axi_kernel_BID,
        m_axi_kernel_BUSER,
        m_axi_image_in_AWVALID,
        m_axi_image_in_AWREADY,
        m_axi_image_in_AWADDR,
        m_axi_image_in_AWID,
        m_axi_image_in_AWLEN,
        m_axi_image_in_AWSIZE,
        m_axi_image_in_AWBURST,
        m_axi_image_in_AWLOCK,
        m_axi_image_in_AWCACHE,
        m_axi_image_in_AWPROT,
        m_axi_image_in_AWQOS,
        m_axi_image_in_AWREGION,
        m_axi_image_in_AWUSER,
        m_axi_image_in_WVALID,
        m_axi_image_in_WREADY,
        m_axi_image_in_WDATA,
        m_axi_image_in_WSTRB,
        m_axi_image_in_WLAST,
        m_axi_image_in_WID,
        m_axi_image_in_WUSER,
        m_axi_image_in_ARVALID,
        m_axi_image_in_ARREADY,
        m_axi_image_in_ARADDR,
        m_axi_image_in_ARID,
        m_axi_image_in_ARLEN,
        m_axi_image_in_ARSIZE,
        m_axi_image_in_ARBURST,
        m_axi_image_in_ARLOCK,
        m_axi_image_in_ARCACHE,
        m_axi_image_in_ARPROT,
        m_axi_image_in_ARQOS,
        m_axi_image_in_ARREGION,
        m_axi_image_in_ARUSER,
        m_axi_image_in_RVALID,
        m_axi_image_in_RREADY,
        m_axi_image_in_RDATA,
        m_axi_image_in_RLAST,
        m_axi_image_in_RID,
        m_axi_image_in_RFIFONUM,
        m_axi_image_in_RUSER,
        m_axi_image_in_RRESP,
        m_axi_image_in_BVALID,
        m_axi_image_in_BREADY,
        m_axi_image_in_BRESP,
        m_axi_image_in_BID,
        m_axi_image_in_BUSER,
        mul_ln7,
        empty_26,
        kernel_size_r,
        add,
        rows,
        sub_i,
        col,
        empty_27,
        cols,
        empty,
        image_in_offset,
        kernel_offset,
        sub16_i,
        mul_i,
        mul35_i,
        sum_1_out,
        sum_1_out_ap_vld,
        grp_fu_235_p_din0,
        grp_fu_235_p_din1,
        grp_fu_235_p_dout0,
        grp_fu_235_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_kernel_AWVALID;
input   m_axi_kernel_AWREADY;
output  [31:0] m_axi_kernel_AWADDR;
output  [0:0] m_axi_kernel_AWID;
output  [31:0] m_axi_kernel_AWLEN;
output  [2:0] m_axi_kernel_AWSIZE;
output  [1:0] m_axi_kernel_AWBURST;
output  [1:0] m_axi_kernel_AWLOCK;
output  [3:0] m_axi_kernel_AWCACHE;
output  [2:0] m_axi_kernel_AWPROT;
output  [3:0] m_axi_kernel_AWQOS;
output  [3:0] m_axi_kernel_AWREGION;
output  [0:0] m_axi_kernel_AWUSER;
output   m_axi_kernel_WVALID;
input   m_axi_kernel_WREADY;
output  [31:0] m_axi_kernel_WDATA;
output  [3:0] m_axi_kernel_WSTRB;
output   m_axi_kernel_WLAST;
output  [0:0] m_axi_kernel_WID;
output  [0:0] m_axi_kernel_WUSER;
output   m_axi_kernel_ARVALID;
input   m_axi_kernel_ARREADY;
output  [31:0] m_axi_kernel_ARADDR;
output  [0:0] m_axi_kernel_ARID;
output  [31:0] m_axi_kernel_ARLEN;
output  [2:0] m_axi_kernel_ARSIZE;
output  [1:0] m_axi_kernel_ARBURST;
output  [1:0] m_axi_kernel_ARLOCK;
output  [3:0] m_axi_kernel_ARCACHE;
output  [2:0] m_axi_kernel_ARPROT;
output  [3:0] m_axi_kernel_ARQOS;
output  [3:0] m_axi_kernel_ARREGION;
output  [0:0] m_axi_kernel_ARUSER;
input   m_axi_kernel_RVALID;
output   m_axi_kernel_RREADY;
input  [31:0] m_axi_kernel_RDATA;
input   m_axi_kernel_RLAST;
input  [0:0] m_axi_kernel_RID;
input  [8:0] m_axi_kernel_RFIFONUM;
input  [0:0] m_axi_kernel_RUSER;
input  [1:0] m_axi_kernel_RRESP;
input   m_axi_kernel_BVALID;
output   m_axi_kernel_BREADY;
input  [1:0] m_axi_kernel_BRESP;
input  [0:0] m_axi_kernel_BID;
input  [0:0] m_axi_kernel_BUSER;
output   m_axi_image_in_AWVALID;
input   m_axi_image_in_AWREADY;
output  [31:0] m_axi_image_in_AWADDR;
output  [0:0] m_axi_image_in_AWID;
output  [31:0] m_axi_image_in_AWLEN;
output  [2:0] m_axi_image_in_AWSIZE;
output  [1:0] m_axi_image_in_AWBURST;
output  [1:0] m_axi_image_in_AWLOCK;
output  [3:0] m_axi_image_in_AWCACHE;
output  [2:0] m_axi_image_in_AWPROT;
output  [3:0] m_axi_image_in_AWQOS;
output  [3:0] m_axi_image_in_AWREGION;
output  [0:0] m_axi_image_in_AWUSER;
output   m_axi_image_in_WVALID;
input   m_axi_image_in_WREADY;
output  [31:0] m_axi_image_in_WDATA;
output  [3:0] m_axi_image_in_WSTRB;
output   m_axi_image_in_WLAST;
output  [0:0] m_axi_image_in_WID;
output  [0:0] m_axi_image_in_WUSER;
output   m_axi_image_in_ARVALID;
input   m_axi_image_in_ARREADY;
output  [31:0] m_axi_image_in_ARADDR;
output  [0:0] m_axi_image_in_ARID;
output  [31:0] m_axi_image_in_ARLEN;
output  [2:0] m_axi_image_in_ARSIZE;
output  [1:0] m_axi_image_in_ARBURST;
output  [1:0] m_axi_image_in_ARLOCK;
output  [3:0] m_axi_image_in_ARCACHE;
output  [2:0] m_axi_image_in_ARPROT;
output  [3:0] m_axi_image_in_ARQOS;
output  [3:0] m_axi_image_in_ARREGION;
output  [0:0] m_axi_image_in_ARUSER;
input   m_axi_image_in_RVALID;
output   m_axi_image_in_RREADY;
input  [31:0] m_axi_image_in_RDATA;
input   m_axi_image_in_RLAST;
input  [0:0] m_axi_image_in_RID;
input  [8:0] m_axi_image_in_RFIFONUM;
input  [0:0] m_axi_image_in_RUSER;
input  [1:0] m_axi_image_in_RRESP;
input   m_axi_image_in_BVALID;
output   m_axi_image_in_BREADY;
input  [1:0] m_axi_image_in_BRESP;
input  [0:0] m_axi_image_in_BID;
input  [0:0] m_axi_image_in_BUSER;
input  [63:0] mul_ln7;
input  [1:0] empty_26;
input  [31:0] kernel_size_r;
input  [31:0] add;
input  [31:0] rows;
input  [29:0] sub_i;
input  [31:0] col;
input  [30:0] empty_27;
input  [31:0] cols;
input  [29:0] empty;
input  [31:0] image_in_offset;
input  [31:0] kernel_offset;
input  [29:0] sub16_i;
input  [29:0] mul_i;
input  [29:0] mul35_i;
output  [31:0] sum_1_out;
output   sum_1_out_ap_vld;
output  [31:0] grp_fu_235_p_din0;
output  [31:0] grp_fu_235_p_din1;
input  [31:0] grp_fu_235_p_dout0;
output   grp_fu_235_p_ce;

reg ap_idle;
reg m_axi_kernel_ARVALID;
reg m_axi_kernel_RREADY;
reg m_axi_image_in_ARVALID;
reg m_axi_image_in_RREADY;
reg sum_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln27_reg_841;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    kernel_blk_n_AR;
wire    ap_block_pp0_stage0;
reg   [0:0] or_ln50_1_reg_929;
reg    kernel_blk_n_R;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] or_ln50_1_reg_929_pp0_iter1_reg;
reg    image_in_blk_n_AR;
reg    image_in_blk_n_R;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] or_ln50_1_reg_929_pp0_iter2_reg;
reg   [29:0] newCol_5_ph_reg_243;
reg    ap_predicate_op136_readreq_state6;
reg    ap_block_state6_io;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] p_cast3_fu_288_p1;
reg   [31:0] p_cast3_reg_836;
wire   [0:0] icmp_ln27_fu_315_p2;
reg    ap_predicate_op165_read_state17;
reg    ap_block_state17_pp0_stage1_iter3;
reg    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln27_reg_841_pp0_iter1_reg;
reg   [0:0] icmp_ln27_reg_841_pp0_iter2_reg;
reg   [0:0] icmp_ln27_reg_841_pp0_iter3_reg;
wire   [63:0] add_ln27_fu_320_p2;
reg   [63:0] add_ln27_reg_845;
reg   [31:0] j_load_reg_850;
wire   [0:0] icmp_ln29_fu_332_p2;
reg   [0:0] icmp_ln29_reg_855;
wire  signed [31:0] select_ln27_fu_343_p3;
reg  signed [31:0] select_ln27_reg_860;
wire   [31:0] select_ln25_fu_351_p3;
reg   [31:0] select_ln25_reg_867;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire   [31:0] newRow_fu_357_p2;
reg   [31:0] newRow_reg_873;
wire   [29:0] empty_38_fu_361_p1;
reg   [29:0] empty_38_reg_882;
wire   [0:0] tmp_3_fu_369_p3;
reg   [0:0] tmp_3_reg_887;
wire   [29:0] newRow_2_fu_404_p3;
reg   [29:0] newRow_2_reg_893;
wire   [31:0] newCol_fu_415_p2;
reg   [31:0] newCol_reg_898;
wire   [29:0] trunc_ln32_fu_421_p1;
reg   [29:0] trunc_ln32_reg_907;
wire   [30:0] trunc_ln32_1_fu_425_p1;
reg   [30:0] trunc_ln32_1_reg_912;
reg   [0:0] tmp_4_reg_917;
wire   [29:0] trunc_ln39_fu_447_p1;
reg   [29:0] trunc_ln39_reg_924;
reg    ap_predicate_op151_readreq_state9;
reg    ap_block_state9_io;
reg    ap_predicate_op162_read_state14;
reg    ap_block_state14_pp0_stage3_iter2;
reg    ap_block_pp0_stage3_11001;
wire   [0:0] or_ln50_1_fu_471_p2;
reg   [0:0] or_ln50_1_reg_929_pp0_iter3_reg;
reg   [0:0] or_ln50_1_reg_929_pp0_iter4_reg;
wire   [31:0] newRow_1_fu_500_p3;
reg   [31:0] newRow_1_reg_933;
wire   [29:0] trunc_ln31_fu_506_p1;
reg   [29:0] trunc_ln31_reg_938;
wire   [31:0] newCol_3_fu_533_p3;
reg   [31:0] newCol_3_reg_944;
wire   [29:0] trunc_ln32_2_fu_539_p1;
reg   [29:0] trunc_ln32_2_reg_949;
wire   [29:0] newCol_1_fu_568_p3;
wire   [29:0] newRow_5_fu_595_p3;
wire    ap_block_pp0_stage4_11001;
wire   [0:0] icmp_ln85_fu_602_p2;
wire   [29:0] newCol_4_fu_611_p2;
reg   [29:0] trunc_ln39_4_reg_975;
wire   [29:0] grp_fu_279_p2;
reg   [29:0] mul_ln39_reg_986;
reg   [29:0] trunc_ln39_1_reg_991;
reg   [31:0] kernel_addr_read_reg_1002;
reg   [31:0] image_in_addr_read_reg_1007;
wire   [31:0] grp_fu_275_p2;
reg   [31:0] mul_reg_1022;
wire   [31:0] grp_fu_271_p2;
reg   [31:0] sum_1_reg_1032;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [29:0] ap_phi_reg_pp0_iter0_newCol_5_ph_reg_243;
reg   [29:0] ap_phi_reg_pp0_iter1_newCol_5_ph_reg_243;
reg  signed [29:0] ap_phi_reg_pp0_iter0_newRow_5_ph_reg_257;
reg  signed [29:0] ap_phi_reg_pp0_iter1_newRow_5_ph_reg_257;
wire  signed [31:0] sext_ln39_1_fu_647_p1;
wire  signed [31:0] sext_ln39_fu_703_p1;
reg   [31:0] j_fu_106;
wire   [31:0] add_ln29_fu_657_p2;
wire    ap_loop_init;
reg   [31:0] i_fu_110;
reg   [63:0] indvar_flatten_fu_114;
reg   [31:0] sum_fu_118;
reg   [31:0] ap_sig_allocacmp_sum_load_1;
reg    ap_block_pp0_stage1_01001;
wire   [31:0] grp_fu_275_p0;
wire   [31:0] grp_fu_275_p1;
wire    ap_block_pp0_stage2;
wire  signed [31:0] icmp_ln29_fu_332_p1;
wire   [31:0] add_ln27_1_fu_337_p2;
wire   [30:0] empty_39_fu_365_p1;
wire   [30:0] empty_40_fu_377_p3;
wire   [31:0] p_cast4_fu_385_p1;
wire   [0:0] ult42_fu_393_p2;
wire   [0:0] rev43_fu_398_p2;
wire   [29:0] empty_41_fu_389_p1;
wire   [31:0] sub_ln32_fu_411_p2;
wire   [0:0] ult_fu_437_p2;
wire   [0:0] icmp_ln50_fu_451_p2;
wire   [0:0] xor_ln50_fu_455_p2;
wire   [0:0] rev_fu_441_p2;
wire   [0:0] or_ln50_fu_466_p2;
wire   [0:0] or_ln50_2_fu_461_p2;
wire   [0:0] abscond_fu_482_p2;
wire   [31:0] neg_fu_477_p2;
wire   [31:0] abs_fu_487_p3;
wire   [31:0] newRow_3_fu_494_p2;
wire   [0:0] abscond2_fu_515_p2;
wire   [31:0] neg1_fu_510_p2;
wire   [31:0] abs3_fu_520_p3;
wire   [31:0] newCol_2_fu_527_p2;
wire   [30:0] select_ln63_fu_543_p3;
wire   [31:0] zext_ln67_fu_549_p1;
wire   [0:0] icmp_ln67_fu_557_p2;
wire   [0:0] xor_ln67_fu_562_p2;
wire   [29:0] trunc_ln67_fu_553_p1;
wire    ap_block_pp0_stage4;
wire   [0:0] icmp_ln77_fu_575_p2;
wire   [29:0] add_ln79_fu_585_p2;
wire   [0:0] xor_ln77_fu_579_p2;
wire   [29:0] newRow_4_fu_590_p2;
wire   [29:0] add_ln87_fu_606_p2;
wire   [29:0] trunc_ln39_2_fu_616_p1;
wire   [29:0] add_ln39_2_fu_619_p2;
wire   [31:0] shl_ln39_1_fu_624_p3;
wire   [31:0] add_ln39_3_fu_632_p2;
wire   [29:0] add_ln39_fu_675_p2;
wire   [31:0] shl_ln1_fu_680_p3;
wire   [31:0] add_ln39_1_fu_688_p2;
reg    grp_fu_271_ce;
reg    grp_fu_275_ce;
reg    grp_fu_279_ce;
reg    grp_fu_284_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage1;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to5;
reg    ap_done_pending_pp0;
wire    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_812;
reg    ap_condition_459;
reg    ap_condition_469;
reg    ap_condition_454;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 j_fu_106 = 32'd0;
#0 i_fu_110 = 32'd0;
#0 indvar_flatten_fu_114 = 64'd0;
#0 sum_fu_118 = 32'd0;
#0 ap_done_reg = 1'b0;
end

LinearImageFilter_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_sig_allocacmp_sum_load_1),
    .din1(mul_reg_1022),
    .ce(grp_fu_271_ce),
    .dout(grp_fu_271_p2)
);

LinearImageFilter_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_275_p0),
    .din1(grp_fu_275_p1),
    .ce(grp_fu_275_ce),
    .dout(grp_fu_275_p2)
);

LinearImageFilter_mul_30s_30s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mul_30s_30s_30_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_reg_pp0_iter1_newRow_5_ph_reg_257),
    .din1(empty),
    .ce(grp_fu_279_ce),
    .dout(grp_fu_279_p2)
);

LinearImageFilter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_812)) begin
        if ((or_ln50_1_fu_471_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_newCol_5_ph_reg_243 <= trunc_ln32_reg_907;
        end else if (((or_ln50_1_fu_471_p2 == 1'd1) & (empty_26 == 2'd0))) begin
            ap_phi_reg_pp0_iter0_newCol_5_ph_reg_243 <= newCol_1_fu_568_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_812)) begin
        if ((or_ln50_1_fu_471_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_newRow_5_ph_reg_257 <= empty_38_reg_882;
        end else if (((or_ln50_1_fu_471_p2 == 1'd1) & (empty_26 == 2'd0))) begin
            ap_phi_reg_pp0_iter0_newRow_5_ph_reg_257 <= newRow_2_reg_893;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_454)) begin
        if ((1'b1 == ap_condition_469)) begin
            ap_phi_reg_pp0_iter1_newCol_5_ph_reg_243 <= trunc_ln32_2_reg_949;
        end else if ((1'b1 == ap_condition_459)) begin
            ap_phi_reg_pp0_iter1_newCol_5_ph_reg_243 <= newCol_4_fu_611_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_newCol_5_ph_reg_243 <= ap_phi_reg_pp0_iter0_newCol_5_ph_reg_243;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln27_reg_841 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln85_fu_602_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln50_1_reg_929 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (empty_26 == 2'd1)) | ((icmp_ln27_reg_841 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln85_fu_602_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln50_1_reg_929 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (empty_26 == 2'd1)))) begin
        ap_phi_reg_pp0_iter1_newRow_5_ph_reg_257 <= newRow_5_fu_595_p3;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_phi_reg_pp0_iter1_newRow_5_ph_reg_257 <= ap_phi_reg_pp0_iter0_newRow_5_ph_reg_257;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_110 <= 32'd0;
        end else if (((icmp_ln27_reg_841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_110 <= select_ln27_reg_860;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_114 <= 64'd0;
        end else if (((icmp_ln27_reg_841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_114 <= add_ln27_reg_845;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_106 <= 32'd0;
        end else if (((icmp_ln27_reg_841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_106 <= add_ln29_fu_657_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_fu_118 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & ((or_ln50_1_reg_929_pp0_iter4_reg == 1'd0) | ((empty_26 == 2'd1) | (empty_26 == 2'd0))))) begin
        sum_fu_118 <= sum_1_reg_1032;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln27_reg_845 <= add_ln27_fu_320_p2;
        icmp_ln27_reg_841 <= icmp_ln27_fu_315_p2;
        icmp_ln27_reg_841_pp0_iter1_reg <= icmp_ln27_reg_841;
        icmp_ln27_reg_841_pp0_iter2_reg <= icmp_ln27_reg_841_pp0_iter1_reg;
        icmp_ln27_reg_841_pp0_iter3_reg <= icmp_ln27_reg_841_pp0_iter2_reg;
        icmp_ln29_reg_855 <= icmp_ln29_fu_332_p2;
        image_in_addr_read_reg_1007 <= m_axi_image_in_RDATA;
        j_load_reg_850 <= j_fu_106;
        mul_ln39_reg_986 <= grp_fu_279_p2;
        select_ln27_reg_860 <= select_ln27_fu_343_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        empty_38_reg_882 <= empty_38_fu_361_p1;
        newCol_reg_898 <= newCol_fu_415_p2;
        newRow_2_reg_893 <= newRow_2_fu_404_p3;
        newRow_reg_873 <= newRow_fu_357_p2;
        select_ln25_reg_867 <= select_ln25_fu_351_p3;
        tmp_3_reg_887 <= newRow_fu_357_p2[32'd31];
        tmp_4_reg_917 <= newCol_fu_415_p2[32'd31];
        trunc_ln32_1_reg_912 <= trunc_ln32_1_fu_425_p1;
        trunc_ln32_reg_907 <= trunc_ln32_fu_421_p1;
        trunc_ln39_1_reg_991 <= {{add_ln39_1_fu_688_p2[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        kernel_addr_read_reg_1002 <= m_axi_kernel_RDATA;
        newCol_3_reg_944 <= newCol_3_fu_533_p3;
        newRow_1_reg_933 <= newRow_1_fu_500_p3;
        or_ln50_1_reg_929 <= or_ln50_1_fu_471_p2;
        or_ln50_1_reg_929_pp0_iter1_reg <= or_ln50_1_reg_929;
        or_ln50_1_reg_929_pp0_iter2_reg <= or_ln50_1_reg_929_pp0_iter1_reg;
        or_ln50_1_reg_929_pp0_iter3_reg <= or_ln50_1_reg_929_pp0_iter2_reg;
        or_ln50_1_reg_929_pp0_iter4_reg <= or_ln50_1_reg_929_pp0_iter3_reg;
        trunc_ln31_reg_938 <= trunc_ln31_fu_506_p1;
        trunc_ln32_2_reg_949 <= trunc_ln32_2_fu_539_p1;
        trunc_ln39_reg_924 <= trunc_ln39_fu_447_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_reg_1022 <= grp_fu_275_p2;
        p_cast3_reg_836[30 : 0] <= p_cast3_fu_288_p1[30 : 0];
        sum_1_reg_1032 <= grp_fu_271_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        newCol_5_ph_reg_243 <= ap_phi_reg_pp0_iter1_newCol_5_ph_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        trunc_ln39_4_reg_975 <= {{add_ln39_3_fu_632_p2[31:2]}};
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_841 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln27_reg_841_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & ((or_ln50_1_reg_929_pp0_iter4_reg == 1'd0) | ((empty_26 == 2'd1) | (empty_26 == 2'd0))))) begin
        ap_sig_allocacmp_sum_load_1 = sum_1_reg_1032;
    end else begin
        ap_sig_allocacmp_sum_load_1 = sum_fu_118;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_271_ce = 1'b1;
    end else begin
        grp_fu_271_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_275_ce = 1'b1;
    end else begin
        grp_fu_275_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_279_ce = 1'b1;
    end else begin
        grp_fu_279_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_284_ce = 1'b1;
    end else begin
        grp_fu_284_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & ((or_ln50_1_reg_929 == 1'd0) | ((empty_26 == 2'd1) | (empty_26 == 2'd0))))) begin
        image_in_blk_n_AR = m_axi_image_in_ARREADY;
    end else begin
        image_in_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & ((or_ln50_1_reg_929_pp0_iter2_reg == 1'd0) | ((empty_26 == 2'd1) | (empty_26 == 2'd0))))) begin
        image_in_blk_n_R = m_axi_image_in_RVALID;
    end else begin
        image_in_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((((icmp_ln27_reg_841 == 1'd0) & (empty_26 == 2'd0)) | ((icmp_ln27_reg_841 == 1'd0) & (empty_26 == 2'd1))) | ((icmp_ln27_reg_841 == 1'd0) & (or_ln50_1_reg_929 == 1'd0))))) begin
        kernel_blk_n_AR = m_axi_kernel_ARREADY;
    end else begin
        kernel_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & ((or_ln50_1_reg_929_pp0_iter1_reg == 1'd0) | ((empty_26 == 2'd1) | (empty_26 == 2'd0))))) begin
        kernel_blk_n_R = m_axi_kernel_RVALID;
    end else begin
        kernel_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op151_readreq_state9 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        m_axi_image_in_ARVALID = 1'b1;
    end else begin
        m_axi_image_in_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op165_read_state17 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m_axi_image_in_RREADY = 1'b1;
    end else begin
        m_axi_image_in_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op136_readreq_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_kernel_ARVALID = 1'b1;
    end else begin
        m_axi_kernel_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op162_read_state14 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        m_axi_kernel_RREADY = 1'b1;
    end else begin
        m_axi_kernel_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln27_reg_841_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_1_out_ap_vld = 1'b1;
    end else begin
        sum_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs3_fu_520_p3 = ((abscond2_fu_515_p2[0:0] == 1'b1) ? newCol_reg_898 : neg1_fu_510_p2);

assign abs_fu_487_p3 = ((abscond_fu_482_p2[0:0] == 1'b1) ? newRow_reg_873 : neg_fu_477_p2);

assign abscond2_fu_515_p2 = (($signed(newCol_reg_898) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign abscond_fu_482_p2 = (($signed(newRow_reg_873) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign add_ln27_1_fu_337_p2 = (i_fu_110 + 32'd1);

assign add_ln27_fu_320_p2 = (indvar_flatten_fu_114 + 64'd1);

assign add_ln29_fu_657_p2 = (select_ln25_reg_867 + 32'd1);

assign add_ln39_1_fu_688_p2 = (shl_ln1_fu_680_p3 + image_in_offset);

assign add_ln39_2_fu_619_p2 = (trunc_ln39_2_fu_616_p1 + trunc_ln39_reg_924);

assign add_ln39_3_fu_632_p2 = (shl_ln39_1_fu_624_p3 + kernel_offset);

assign add_ln39_fu_675_p2 = (mul_ln39_reg_986 + newCol_5_ph_reg_243);

assign add_ln79_fu_585_p2 = ($signed(mul_i) + $signed(30'd1073741823));

assign add_ln87_fu_606_p2 = ($signed(mul35_i) + $signed(30'd1073741823));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage1_iter3));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage1_iter3));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage1_iter3));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage3_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage3_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage3_iter2 = ((ap_predicate_op162_read_state14 == 1'b1) & (m_axi_kernel_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state17_pp0_stage1_iter3 = ((ap_predicate_op165_read_state17 == 1'b1) & (m_axi_image_in_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state6_io = ((m_axi_kernel_ARREADY == 1'b0) & (ap_predicate_op136_readreq_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state9_io = ((ap_predicate_op151_readreq_state9 == 1'b1) & (m_axi_image_in_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_454 = ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4));
end

always @ (*) begin
    ap_condition_459 = ((icmp_ln27_reg_841 == 1'd0) & (icmp_ln85_fu_602_p2 == 1'd0) & (or_ln50_1_reg_929 == 1'd1) & (empty_26 == 2'd1));
end

always @ (*) begin
    ap_condition_469 = ((icmp_ln27_reg_841 == 1'd0) & (icmp_ln85_fu_602_p2 == 1'd1) & (or_ln50_1_reg_929 == 1'd1) & (empty_26 == 2'd1));
end

always @ (*) begin
    ap_condition_812 = ((icmp_ln27_reg_841 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

always @ (*) begin
    ap_predicate_op136_readreq_state6 = ((((icmp_ln27_reg_841 == 1'd0) & (empty_26 == 2'd0)) | ((icmp_ln27_reg_841 == 1'd0) & (empty_26 == 2'd1))) | ((icmp_ln27_reg_841 == 1'd0) & (or_ln50_1_reg_929 == 1'd0)));
end

always @ (*) begin
    ap_predicate_op151_readreq_state9 = ((or_ln50_1_reg_929 == 1'd0) | ((empty_26 == 2'd1) | (empty_26 == 2'd0)));
end

always @ (*) begin
    ap_predicate_op162_read_state14 = ((or_ln50_1_reg_929_pp0_iter1_reg == 1'd0) | ((empty_26 == 2'd1) | (empty_26 == 2'd0)));
end

always @ (*) begin
    ap_predicate_op165_read_state17 = ((or_ln50_1_reg_929_pp0_iter2_reg == 1'd0) | ((empty_26 == 2'd1) | (empty_26 == 2'd0)));
end

assign empty_38_fu_361_p1 = newRow_fu_357_p2[29:0];

assign empty_39_fu_365_p1 = newRow_fu_357_p2[30:0];

assign empty_40_fu_377_p3 = ((tmp_3_fu_369_p3[0:0] == 1'b1) ? 31'd0 : empty_39_fu_365_p1);

assign empty_41_fu_389_p1 = empty_40_fu_377_p3[29:0];

assign grp_fu_235_p_ce = grp_fu_284_ce;

assign grp_fu_235_p_din0 = select_ln27_reg_860;

assign grp_fu_235_p_din1 = kernel_size_r;

assign grp_fu_275_p0 = image_in_addr_read_reg_1007;

assign grp_fu_275_p1 = kernel_addr_read_reg_1002;

assign icmp_ln27_fu_315_p2 = ((indvar_flatten_fu_114 == mul_ln7) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_332_p1 = kernel_size_r;

assign icmp_ln29_fu_332_p2 = ((j_fu_106 == icmp_ln29_fu_332_p1) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_451_p2 = ((newCol_reg_898 < cols) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_557_p2 = ((zext_ln67_fu_549_p1 < cols) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_575_p2 = ((newRow_1_reg_933 < rows) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_602_p2 = ((newCol_3_reg_944 < cols) ? 1'b1 : 1'b0);

assign m_axi_image_in_ARADDR = sext_ln39_fu_703_p1;

assign m_axi_image_in_ARBURST = 2'd0;

assign m_axi_image_in_ARCACHE = 4'd0;

assign m_axi_image_in_ARID = 1'd0;

assign m_axi_image_in_ARLEN = 32'd1;

assign m_axi_image_in_ARLOCK = 2'd0;

assign m_axi_image_in_ARPROT = 3'd0;

assign m_axi_image_in_ARQOS = 4'd0;

assign m_axi_image_in_ARREGION = 4'd0;

assign m_axi_image_in_ARSIZE = 3'd0;

assign m_axi_image_in_ARUSER = 1'd0;

assign m_axi_image_in_AWADDR = 32'd0;

assign m_axi_image_in_AWBURST = 2'd0;

assign m_axi_image_in_AWCACHE = 4'd0;

assign m_axi_image_in_AWID = 1'd0;

assign m_axi_image_in_AWLEN = 32'd0;

assign m_axi_image_in_AWLOCK = 2'd0;

assign m_axi_image_in_AWPROT = 3'd0;

assign m_axi_image_in_AWQOS = 4'd0;

assign m_axi_image_in_AWREGION = 4'd0;

assign m_axi_image_in_AWSIZE = 3'd0;

assign m_axi_image_in_AWUSER = 1'd0;

assign m_axi_image_in_AWVALID = 1'b0;

assign m_axi_image_in_BREADY = 1'b0;

assign m_axi_image_in_WDATA = 32'd0;

assign m_axi_image_in_WID = 1'd0;

assign m_axi_image_in_WLAST = 1'b0;

assign m_axi_image_in_WSTRB = 4'd0;

assign m_axi_image_in_WUSER = 1'd0;

assign m_axi_image_in_WVALID = 1'b0;

assign m_axi_kernel_ARADDR = sext_ln39_1_fu_647_p1;

assign m_axi_kernel_ARBURST = 2'd0;

assign m_axi_kernel_ARCACHE = 4'd0;

assign m_axi_kernel_ARID = 1'd0;

assign m_axi_kernel_ARLEN = 32'd1;

assign m_axi_kernel_ARLOCK = 2'd0;

assign m_axi_kernel_ARPROT = 3'd0;

assign m_axi_kernel_ARQOS = 4'd0;

assign m_axi_kernel_ARREGION = 4'd0;

assign m_axi_kernel_ARSIZE = 3'd0;

assign m_axi_kernel_ARUSER = 1'd0;

assign m_axi_kernel_AWADDR = 32'd0;

assign m_axi_kernel_AWBURST = 2'd0;

assign m_axi_kernel_AWCACHE = 4'd0;

assign m_axi_kernel_AWID = 1'd0;

assign m_axi_kernel_AWLEN = 32'd0;

assign m_axi_kernel_AWLOCK = 2'd0;

assign m_axi_kernel_AWPROT = 3'd0;

assign m_axi_kernel_AWQOS = 4'd0;

assign m_axi_kernel_AWREGION = 4'd0;

assign m_axi_kernel_AWSIZE = 3'd0;

assign m_axi_kernel_AWUSER = 1'd0;

assign m_axi_kernel_AWVALID = 1'b0;

assign m_axi_kernel_BREADY = 1'b0;

assign m_axi_kernel_WDATA = 32'd0;

assign m_axi_kernel_WID = 1'd0;

assign m_axi_kernel_WLAST = 1'b0;

assign m_axi_kernel_WSTRB = 4'd0;

assign m_axi_kernel_WUSER = 1'd0;

assign m_axi_kernel_WVALID = 1'b0;

assign neg1_fu_510_p2 = (32'd0 - newCol_reg_898);

assign neg_fu_477_p2 = (32'd0 - newRow_reg_873);

assign newCol_1_fu_568_p3 = ((xor_ln67_fu_562_p2[0:0] == 1'b1) ? sub16_i : trunc_ln67_fu_553_p1);

assign newCol_2_fu_527_p2 = ($signed(abs3_fu_520_p3) + $signed(32'd4294967295));

assign newCol_3_fu_533_p3 = ((tmp_4_reg_917[0:0] == 1'b1) ? newCol_2_fu_527_p2 : newCol_reg_898);

assign newCol_4_fu_611_p2 = (add_ln87_fu_606_p2 - trunc_ln32_2_reg_949);

assign newCol_fu_415_p2 = (select_ln25_fu_351_p3 + sub_ln32_fu_411_p2);

assign newRow_1_fu_500_p3 = ((tmp_3_reg_887[0:0] == 1'b1) ? newRow_3_fu_494_p2 : newRow_reg_873);

assign newRow_2_fu_404_p3 = ((rev43_fu_398_p2[0:0] == 1'b1) ? sub_i : empty_41_fu_389_p1);

assign newRow_3_fu_494_p2 = ($signed(abs_fu_487_p3) + $signed(32'd4294967295));

assign newRow_4_fu_590_p2 = (add_ln79_fu_585_p2 - trunc_ln31_reg_938);

assign newRow_5_fu_595_p3 = ((xor_ln77_fu_579_p2[0:0] == 1'b1) ? newRow_4_fu_590_p2 : trunc_ln31_reg_938);

assign newRow_fu_357_p2 = ($signed(select_ln27_reg_860) + $signed(add));

assign or_ln50_1_fu_471_p2 = (or_ln50_fu_466_p2 | or_ln50_2_fu_461_p2);

assign or_ln50_2_fu_461_p2 = (xor_ln50_fu_455_p2 | tmp_4_reg_917);

assign or_ln50_fu_466_p2 = (tmp_3_reg_887 | rev_fu_441_p2);

assign p_cast3_fu_288_p1 = empty_27;

assign p_cast4_fu_385_p1 = empty_40_fu_377_p3;

assign rev43_fu_398_p2 = (ult42_fu_393_p2 ^ 1'd1);

assign rev_fu_441_p2 = (ult_fu_437_p2 ^ 1'd1);

assign select_ln25_fu_351_p3 = ((icmp_ln29_reg_855[0:0] == 1'b1) ? 32'd0 : j_load_reg_850);

assign select_ln27_fu_343_p3 = ((icmp_ln29_fu_332_p2[0:0] == 1'b1) ? add_ln27_1_fu_337_p2 : i_fu_110);

assign select_ln63_fu_543_p3 = ((tmp_4_reg_917[0:0] == 1'b1) ? 31'd0 : trunc_ln32_1_reg_912);

assign sext_ln39_1_fu_647_p1 = $signed(trunc_ln39_4_reg_975);

assign sext_ln39_fu_703_p1 = $signed(trunc_ln39_1_reg_991);

assign shl_ln1_fu_680_p3 = {{add_ln39_fu_675_p2}, {2'd0}};

assign shl_ln39_1_fu_624_p3 = {{add_ln39_2_fu_619_p2}, {2'd0}};

assign sub_ln32_fu_411_p2 = (col - p_cast3_reg_836);

assign sum_1_out = sum_fu_118;

assign tmp_3_fu_369_p3 = newRow_fu_357_p2[32'd31];

assign trunc_ln31_fu_506_p1 = newRow_1_fu_500_p3[29:0];

assign trunc_ln32_1_fu_425_p1 = newCol_fu_415_p2[30:0];

assign trunc_ln32_2_fu_539_p1 = newCol_3_fu_533_p3[29:0];

assign trunc_ln32_fu_421_p1 = newCol_fu_415_p2[29:0];

assign trunc_ln39_2_fu_616_p1 = select_ln25_reg_867[29:0];

assign trunc_ln39_fu_447_p1 = grp_fu_235_p_dout0[29:0];

assign trunc_ln67_fu_553_p1 = select_ln63_fu_543_p3[29:0];

assign ult42_fu_393_p2 = ((p_cast4_fu_385_p1 < rows) ? 1'b1 : 1'b0);

assign ult_fu_437_p2 = ((newRow_reg_873 < rows) ? 1'b1 : 1'b0);

assign xor_ln50_fu_455_p2 = (icmp_ln50_fu_451_p2 ^ 1'd1);

assign xor_ln67_fu_562_p2 = (icmp_ln67_fu_557_p2 ^ 1'd1);

assign xor_ln77_fu_579_p2 = (icmp_ln77_fu_575_p2 ^ 1'd1);

assign zext_ln67_fu_549_p1 = select_ln63_fu_543_p3;

always @ (posedge ap_clk) begin
    p_cast3_reg_836[31] <= 1'b0;
end

endmodule //LinearImageFilter_LinearImageFilter_Pipeline_ker_rows_loop_ker_cols_loop
